#!/usr/bin/perl

# -- Touch the /Library/Extensions dir, and load our kext

system("echo 'kext postinstall script-----'");
system("sudo touch /Library/Extensions");
system("sudo kextload /Library/Extensions/Soundflower.kext");

exit(0);
