#!/usr/bin/perl

# -- Unload our kext, if it exists, then delete it
# -- for some reason kextunload fails sometimes on the first try
# -- so am calling it twice to make sure

system("echo 'kext preupgrade script-----'");
system("sudo kextunload /Library/Extensions/Soundflower.kext");
system("sudo kextunload /Library/Extensions/Soundflower.kext");
system("sudo rm -rf /Library/Extensions/Soundflower.kext");

exit(0);
