#!/bin/bash

echo "touch the extensions directory"
chown -R root  /Library/Extensions/Soundflower.kext
chgrp -R wheel /Library/Extensions/Soundflower.kext
chmod -R 755   /Library/Extensions/Soundflower.kext
touch /Library/Extensions
kextload /Library/Extensions/Soundflower.kext
